Repository prgrms-aibe-devcourse/AIBE1-FinalProject-Team01-FE, pull requests merged in 2025-07, with the labels that each got.

#41 Feat: 로컬 로그인 기능 구현 #36
  src/components/auth/LoginForm.jsx
  src/components/main/PopularPosts.jsx
  src/context/AuthContext.jsx
  src/services/api.js
  src/styles/components/auth/auth.css
Labels: Feat

#48 Fix : 쿠키 도메인 오류로 인한 API 연동 문제 해결 #36
  .env
  .gitignore
  src/components/auth/LoginForm.jsx
  src/components/main/PopularPosts.jsx
  src/context/AuthContext.jsx
  src/services/api.js
Labels: Fix

#56 Fix: 로그인 상태 유지 및 인증 에러 처리 개선 #36
  src/context/AuthContext.jsx
  src/services/api.js
Labels: Fix

#67 Feat: 함께해요 게시판 API 연결
  .gitignore
  src/components/comment/CommentItem.jsx
  src/components/together/MarketBoardDetail.jsx
  src/components/together/TogetherBoardDetail.jsx
  src/components/together/TogetherBoardList.jsx
  src/components/together/TogetherPostInfo.jsx
  src/hooks/useLikeBookmark.js
  src/hooks/useTogetherPosts.js
  src/pages/community/CommunityBoardDetailPage.jsx
  src/pages/hub/HubDetailPage.jsx
  src/pages/info/InfoBoardDetailPage.jsx
  src/pages/together/TogetherBoardDetailPage.jsx
  src/pages/together/TogetherPage.jsx
  src/pages/together/TogetherWritePage.jsx
  src/router/Router.jsx
  src/services/bookmarkApi.js
  src/services/likeApi.js
  src/services/together/gatheringApi.js
  src/services/together/marketApi.js
  src/services/together/matchingApi.js
Labels: Feat

#68 Feat: 이미지 업로드 API 연결 및 화면에 이미지 출력
  src/hooks/useImageUpload.js
  src/services/imageApi.js
  src/styles/components/common/PostContent.css
  src/styles/components/editor/editor.css
Labels: Feat, Design

#77 Chore: 0712 프론트엔드 배포
  .gitignore
  src/components/board/BoardPostHeader.jsx
  src/components/board/BoardSearchBar.jsx
  src/components/comment/CommentItem.jsx
  src/components/common/AlarmDropdown.jsx
  src/components/community/CommunityBoardDetail.jsx
  src/components/hub/HubBoardList.jsx
  src/components/hub/HubPostInfo.jsx
  src/components/hub/HubSearchBar.jsx
  src/components/info/InfoBoardDetail.jsx
  src/components/together/MarketBoardDetail.jsx
  src/components/together/TogetherBoardDetail.jsx
  src/components/together/TogetherBoardList.jsx
  src/components/together/TogetherPostInfo.jsx
  src/context/AuthContext.jsx
  src/hooks/useAlarms.js
  src/hooks/useCommunityPosts.js
  src/hooks/useImageUpload.js
  src/hooks/useLikeBookmark.js
  src/hooks/useSSE.js
  src/hooks/useTogetherPosts.js
  src/pages/community/CommunityBoardDetailPage.jsx
  src/pages/community/CommunityPage.jsx
  src/pages/hub/HubDetailPage.jsx
  src/pages/info/InfoBoardDetailPage.jsx
  src/pages/info/InfoPage.jsx
  src/pages/info/InfoWritePage.jsx
  src/pages/together/TogetherBoardDetailPage.jsx
  src/pages/together/TogetherPage.jsx
  src/pages/together/TogetherWritePage.jsx
  src/router/Router.jsx
  src/services/alarmApi.js
  src/services/bookmarkApi.js
  src/services/imageApi.js
  src/services/infoApi.js
  src/services/likeApi.js
  src/services/together/gatheringApi.js
  src/services/together/marketApi.js
  src/services/together/matchingApi.js
  src/styles/components/common/PostContent.css
  src/styles/components/editor/editor.css
  src/utils/auth.js
  src/utils/hub.js
Labels: Chore

#82 Feat: 로컬 회원가입 기능 완성 #70
  src/components/auth/LoginForm.jsx
  src/components/auth/ProfileForm.jsx
  src/components/auth/SignupForm.jsx
  src/constants/topics.js
  src/context/AuthContext.jsx
  src/pages/auth/ProfileSetupPage.jsx
  src/pages/mypage/ChangePasswordPage.jsx
  src/services/api.js
  src/services/authApi.js
  src/styles/components/auth/auth.css
  src/utils/auth.js
Labels: Feat

#85 Feat: 로컬 회원가입 기능 완성 #70
  src/components/auth/LoginForm.jsx
  src/components/auth/ProfileForm.jsx
  src/components/auth/SignupForm.jsx
  src/constants/topics.js
  src/context/AuthContext.jsx
  src/pages/auth/ProfileSetupPage.jsx
  src/services/api.js
  src/services/authApi.js
  src/styles/components/auth/auth.css
  src/utils/auth.js
Labels: Feat

#86 Refactor: 로그인 기능 개선 #73
  src/components/auth/LoginForm.jsx
  src/components/auth/ProfileForm.jsx
  src/components/auth/SignupForm.jsx
  src/context/AuthContext.jsx
  src/services/api.js
  src/styles/components/auth/auth.css
  src/utils/auth.js
  src/utils/tokenManager.js
Labels: Refactor

#87 Fix: 북마크 하드코딩 제거
  src/hooks/useLikeBookmark.js
  src/pages/together/constants.js
  src/pages/together/togetherData.js
  src/router/Router.jsx
  src/services/bookmarkApi.js
Labels: Fix, Refactor

#89 Feat: 소셜 로그인 연동 #71
  src/components/auth/LoginForm.jsx
  src/context/AuthContext.jsx
  src/pages/auth/OAuthCallbackPage.jsx
  src/pages/auth/ProfileSetupPage.jsx
  src/router/Router.jsx
  src/services/api.js
  src/utils/tokenManager.js
Labels: Feat

#88 Feat: 함께해요 게시글 수정, 삭제
  src/components/board/BoardPostHeader.jsx
  src/components/together/TogetherBoardDetail.jsx
  src/pages/together/TogetherWritePage.jsx
  src/router/Router.jsx
Labels: Feat, Fix, Refactor

#91 Feat : 로그아웃 및 토큰 재발급 기능 구현 #72
  src/components/auth/LoginForm.jsx
  src/context/AuthContext.jsx
  src/services/api.js
  src/services/authApi.js
Labels: Feat

#93 HOTFIX: 이미지 깨짐 수정
  src/styles/components/editor/editor.css
Labels: Fix

#112 Feat: 토픽 선택 백엔드 동기화 및 수강생 인증 폼 구현 #103
  src/components/mypage/EditProfileForm.jsx
  src/components/mypage/ProfileSummary.jsx
  src/components/mypage/StudentVerificationForm.jsx
  src/constants/topics.js
  src/pages/auth/ProfileSetupPage.jsx
  src/pages/mypage/MyPage.jsx
  src/styles/components/mypage/mypage.css
  src/utils/provider.js
Labels: Feat

#113 Feat: 수강생 인증 연결 및 리팩터링
  src/components/common/NavigationBar.jsx
  src/components/main/PopularPosts.jsx
  src/components/mypage/StudentVerificationForm.jsx
  src/pages/auth/LoginPage.jsx
  src/pages/auth/OAuthCallbackPage.jsx
  src/pages/auth/ProfileSetupPage.jsx
  src/pages/auth/SignupPage.jsx
  src/pages/community/CommunityBoardDetailPage.jsx
  src/pages/community/CommunityPage.jsx
  src/pages/community/CommunityWritePage.jsx
  src/pages/dm/DMPage.jsx
  src/pages/hub/HubDetailPage.jsx
  src/pages/hub/HubPage.jsx
  src/pages/hub/HubWritePage.jsx
  src/pages/info/InfoBoardDetailPage.jsx
  src/pages/info/InfoPage.jsx
  src/pages/info/InfoWritePage.jsx
  src/pages/main/MainPage.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/together/TogetherBoardDetailPage.jsx
  src/pages/together/TogetherPage.jsx
  src/pages/together/TogetherWritePage.jsx
  src/router/Router.jsx
  src/services/verifyApi.js
  src/styles/components/auth/auth.css
  src/styles/components/common/NavigationBar.css
Labels: Feat, Fix

#117 Fix : 로그인 에러 메시지 및 프로필 폼 에러 처리 개선
  src/components/auth/LoginForm.jsx
  src/components/auth/ProfileForm.jsx
  src/services/api.js
  src/styles/components/auth/auth.css
Labels: Fix

#119 Feat: 수강생 인증 페이지 모달 추가 및 일부 리팩터링
  src/assets/example/1.jpg
  src/assets/example/2.jpg
  src/components/common/NavigationBar.jsx
  src/components/main/PopularPosts.jsx
  src/components/mypage/EditProfileForm.jsx
  src/components/mypage/ProfileSummary.jsx
  src/components/mypage/StudentVerificationForm.jsx
  src/pages/mypage/MyPage.jsx
  src/styles/components/mypage/mypage.css
  src/styles/components/mypage/verifyForm.css
Labels: Feat, Style

#121 Style: 각종 css 버그 수정 #110
  src/components/board/BoardPostHeader.jsx
  src/components/community/CommunityBoardDetail.jsx
  src/components/info/InfoBoardDetail.jsx
  src/components/together/MarketPostInfo.jsx
  src/components/together/TogetherBoardDetail.jsx
  src/components/together/TogetherPostInfo.jsx
  src/pages/community/constants.js
  src/pages/together/TogetherBoardDetailPage.jsx
  src/services/together/gatheringApi.js
  src/services/together/marketApi.js
  src/services/together/matchingApi.js
  src/styles/components/together/postinfo.css
  src/utils/board.js
Labels: Style

#124 Feat : 비밀번호 재설정 연동 #123
  src/App.jsx
  src/components/auth/FindPasswordForm.jsx
  src/components/auth/ResetPasswordForm.jsx
  src/pages/auth/ResetPasswordPage.jsx
  src/router/Router.jsx
  src/services/api.js
Labels: Feat

#126 Feat: 팁탭 에디터 스크롤, 이미지 붙여넣기 기능 추가 #125
  src/components/editor/CustomTiptapEditor.jsx
  src/hooks/useImageUpload.js
  src/styles/components/common/PostContent.css
  src/styles/components/editor/editor.css
Labels: Feat

#136 Refactor: 마이페이지 프로필 관리 기능 개선
  src/components/mypage/EditProfileForm.jsx
  src/components/mypage/ProfileSummary.jsx
  src/context/AuthContext.jsx
  src/pages/mypage/MyPage.jsx
  src/services/accountApi.js
  src/styles/components/mypage/mypage.css
Labels: Refactor

#138 Style: 프로젝트 허브 및 댓글 CSS 개선 #137
  src/components/board/BoardTagShareBar.jsx
  src/components/comment/CommentItem.jsx
  src/components/comment/CommentSection.jsx
  src/components/hub/HubPostInfo.jsx
  src/pages/hub/HubWritePage.jsx
  src/styles/components/comment/CommentSection.css
  src/styles/components/community/community.css
  src/styles/components/hub/hub.css
  src/utils/date.js
Labels: Style

#139 Chore: 0716 프론트엔드 배포
  src/components/board/BoardTagShareBar.jsx
  src/components/comment/CommentItem.jsx
  src/components/comment/CommentSection.jsx
  src/components/dm/DMSidebar.jsx
  src/components/hub/HubPostInfo.jsx
  src/components/mypage/EditProfileForm.jsx
  src/components/mypage/FollowCard.jsx
  src/components/mypage/FollowList.jsx
  src/components/mypage/MyPageSidebar.jsx
  src/components/mypage/ProfileSummary.jsx
  src/components/user/UserInfoModal.jsx
  src/context/AuthContext.jsx
  src/hooks/useFollowList.js
  src/pages/hub/HubWritePage.jsx
  src/pages/mypage/MyPage.jsx
  src/services/accountApi.js
  src/services/followApi.js
  src/styles/components/comment/CommentSection.css
  src/styles/components/community/community.css
  src/styles/components/hub/hub.css
  src/styles/components/mypage/followcard.css
  src/styles/components/mypage/followlist.css
  src/styles/components/mypage/mypage.css
  src/utils/date.js
Labels: Chore

#147 Fix: 인증 관련 이슈 통합 수정
  src/components/board/BoardPostHeader.jsx
  src/components/comment/CommentItem.jsx
  src/components/common/UserInfo.jsx
  src/components/mypage/EditProfileForm.jsx
  src/context/AuthContext.jsx
  src/pages/auth/ProfileSetupPage.jsx
  src/router/Router.jsx
Labels: Fix

#151 Refactor: 페이지 전환 UX 개선 #152
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/MicroInteractions.jsx
  src/components/common/PageTransition.jsx
  src/components/common/ScrollAnimations.jsx
  src/components/common/SharedElementTransition.jsx
  src/main.jsx
  src/pages/community/CommunityPage.jsx
  src/router/Router.jsx
  src/styles/scrollbar.css
Labels: Refactor

#160 Fix: 소셜 로그인 사용자 프로필 완성 강제 기능 및 UX 개선
  src/App.jsx
  src/components/common/NavigationBar.jsx
  src/components/main/MainStatusSection.jsx
  src/components/mypage/WithdrawPage.jsx
  src/pages/auth/ProfileSetupPage.jsx
  src/router/Router.jsx
Labels: Fix
